План анализа:

1. Общий график + описание. Разных больше, чем одинаковых. Гипотеза не подтвердилась. 
2. График и таблица по отдельным словам. Видно, что разница в ответах. Фишер говорит, что значимо. Но если сравнивать похожие по ответам столбцы (например, два последних), то стат значимости нет. Вывод: надо соединить столбики с похожими группами и посмотреть, будет ли стат значимость там. 
3. Проверка стат значимости из п. 2
4. Когда станет понятно, посмотреть на ответы, которые участники эксперимента предлагают по отдельным стимулам
5 от пола (нет)
6. Проверим, есть ли зависимость от муз образ (нет)
7. Проверим, есть ли зависимость от линг образ (да)
8. Проверим, есть ли зависимость от колич языков (да)
9. Проверим, есть ли зависимость от длины слова (да)
10. Проверим, есть ли зависимость от состояния (да)
11. Проверим, не скоррелированы ли пп. 7 и 8 (скоррелированы: получаются, они влияют на ответы как один общий фактор, их невозможно разделить).
12. Проверим, угадывают ли участники состояние (выше ли процент называния, чем случайная вероятность)

13. Логистическая регрессия

0. Ставим пакеты 

library(stringr)
library(tidyverse)
library(ggplot2)
library(dplyr)


# график ответов (общий)

We expected that all participants of the experiment would consider the stimuli pairs as one word. If at least one subject decides that there are two different words among the stimuli pairs, we will consider our hypothesis incorrect. 

data = read.csv("analysis.csv")
barplot(table(data$stimulus), ylab='Number of responses', main='Identical/Different Distribution', col = 'pink')

The graph consists of three columns, which contain the answers of participants in the experiment. The abscissa axis contains the response options, and the ordinate axis indicates the number of responses from the participants. The barplot presents that in the total for stimuli the “different” answer option exceeds the “identical” option. Some subjects could not determine whether a pair of stimuli was different words or the same. On the graph, this is the first column without a title; it will not be taken into account with further analysis.

# график ответов (отдельные пары стимулов). подумать, как смэтчить и трактовать результаты теста (отличается только? одно? слово, проверить всех носителей на понятность)

The following barplot manifests grouping responses by stimuli names. The abscissa axis contains names of stimuli pairs, and the ordinate axis presents the number of responses from the participants. It is clearly seen that the columns vary greatly in values. By applying Fisher's Exact Test to the resulting contingency table, we obtained a low value of p-value (p-value = 6e-05 < 0.05). It allows to consider the difference between the columns statistically significant. However, if the test is applied to two random columns (for example, for tonus.konus and czaplya.kaplya), then p-value will be high (p-value = 0.2191 > 0.05) and will not indicate statistical significance. Thus, it is required to connect the columns with similar values to check which data is actually different from each other.


#расформировать и доделать

data = read.csv("analysis.csv")
data$really = (sapply(data$really, as.character))
data [data$really %in% c('tot.kot','stol.skol','tort.kort','stolko.skolko','tomik.komik','tonus.konus', 'tsaplya.kaplya'),]  %>% 
  na.omit() %>% 
  count(really,stimulus) %>% 
  spread(key = really, value = n) %>% 
  mutate(tot.kot = ifelse(is.na(`tot.kot`), as.integer(0), `tot.kot`),
         stol.skol = ifelse(is.na(`stol.skol`), as.integer(0), `stol.skol`),  
         tort.kort = ifelse(is.na(`tort.kort`), as.integer(0), `tort.kort`),
         stolko.skolko = ifelse(is.na(`stolko.skolko`), as.integer(0), `stolko.skolko`),  
         tomik.komik = ifelse(is.na(`tomik.komik`), as.integer(0), `tomik.komik`),  
         tonus.konus = ifelse(is.na(`tonus.konus`), as.integer(0), `tonus.konus`),  
         tsaplya.kaplya = ifelse(is.na(`tsaplya.kaplya`), as.integer(0), `tsaplya.kaplya`),  
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, tot.kot, stol.skol, 	tort.kort, stolko.skolko, tomik.komik, 	tonus.konus, tsaplya.kaplya) ->
  data_test
data_test = data_test[2:3,-1]
test = data_test
row.names(test)[1] <- 'Different'
row.names(test)[2] <- 'Identical'
test <- stack(test)
test$variant <- rep(c('Different','Identical'),7)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  coord_flip()+
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 13))) +
  geom_bar(stat="identity", position=position_dodge())

#пол не влияет на ответы

The graph indicates distribution of responses by gender. The abscissa axis contains options of answer, and the ordinate axis presents the number of responses from the participants. By applying Fisher's Exact Test to the resulting contingency table, we obtained a very high p-value (p-value = 1 > 0.05); therefore, the differences are not statistically significant, and we have no reason to discard the alternative hypothesis. Thus, according to the data, gender does not affect respondents' answers. 

data = read.csv("analysis.csv")
data$gender = sapply(data$gender, as.character)
data [data$gender %in% c('f','m'),] %>%
  na.omit() %>% 
  count(gender,stimulus) %>% 
  spread(key = gender, value = n) %>% 
  mutate(f = ifelse(is.na(`f`), as.integer(0), `f`),  
         m = ifelse(is.na(`m`), as.integer(0), `m`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, f, m) ->
  data_test
data_test = data_test[2:3,-1]
data_test
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)

Fisher's Exact Test for Count Data
data:  data_test
p-value = 1
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.7105923 1.3914761
sample estimates:
odds ratio 
 0.9945437 

test = data_test
row.names(test)[1] <- 'Different'
row.names(test)[2] <- 'Identical'
test <- stack(test)
test$variant <- rep(c('Different','Identical'),2)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 14))) +
  geom_bar(stat="identity", position=position_dodge())
  
#муз образование не влияет на ответы


The following bar plot manifests distribution of responses by musical experience. Subject thought that it was the main aim of current study. The abscissa axis contains options of answer, and the ordinate axis presents the number of responses from the participants. The graph presents slight difference between respondents with (left column) and without musical experience (right column). Subjects with musical education evaluate stimuli pairs more as two different words; and the answers of the participants without musical education are distributed approximately equally in two columns. By applying Fisher's Exact Test to the resulting contingency table, we acquired a high p-value (p-value = 0.1165 > 0.05); therefore, the differences are not statistically significant, and we have no reason to discard the alternative hypothesis. Thus, according to the data, musical experience does not affect respondents’ answers. 

library(stringr)
library(tidyverse)
library(dplyr)

data = read.csv("analysis.csv") #грузим данные
data$music = sapply(data$music, as.character) #выбираем, что хотим анализировать
data [data$music %in% c('yes','no'),] %>% #расформировываем столбец в несколько на основании значений
  na.omit() %>% #игнорируем NA
  count(music,stimulus) %>% #выбираем даныые, которые нужно учесть при анализе
  spread(key = music, value = n) %>% #key - имя столбца/позиции передается в value (счет)
  mutate(yes = ifelse(is.na(`yes`), as.integer(0), `yes`),  #меняем таблицу: is.na() считаем 0 и вписываем нужные значения
         no = ifelse(is.na(`no`), as.integer(0), `no`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, yes, no) ->
  data_test
data_test = data_test[2:3,-1]
#data_test
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)

	Fisher's Exact Test for Count Data

data:  data_test
p-value = 0.1165
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.9257751 1.8994032
sample estimates:
odds ratio 
  1.324402 

test = data_test
row.names(test)[1] <- 'Different'
row.names(test)[2] <- 'Identical'
test <- stack(test)
test$variant <- rep(c('Different','Identical'),2)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 14))) +
  geom_bar(stat="identity", position=position_dodge())
  

#иняз общее

(The barplot presents/indicates/manifests that...)

data = read.csv("analysis.csv") #грузим данные
data$foreign = sapply(data$foreign, as.numeric) #выбираем, что хотим анализировать
data [data$foreign %in% c('0','1','2','3','4','6'),] %>% #расформировываем столбец в несколько на основании значений
  na.omit() %>% #игнорируем NA
  count(foreign,stimulus) %>% #выбираем даныые, которые нужно учесть при анализе
  spread(key = foreign, value = n) %>% #key - имя столбца/позиции передается в value (считает)
  mutate(zero = ifelse(is.na(`0`), as.integer(0), `0`),  #меняем таблицу: is.na() считаем 0 и вписываем нужные значения
         one = ifelse(is.na(`1`), as.integer(0), `1`),
         two = ifelse(is.na(`2`), as.integer(0), `2`),
         three = ifelse(is.na(`3`), as.integer(0), `3`),
         four = ifelse(is.na(`4`), as.integer(0), `4`),
         six = ifelse(is.na(`6`), as.integer(0), `6`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, zero, one, two, three, four, six) ->
  data_test
data_test = data_test[2:3,-1]
data_test
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)

#p-value = 0.00047

test = data_test
row.names(test)[1] <- 'Different'
row.names(test)[2] <- 'Identical'
test <- stack(test)
test$variant <- rep(c('Different','Identical'),6)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 14))) +
  geom_bar(stat="identity", position=position_dodge())
  
  
#лингобр влияет на ответы

data = read.csv("analysis.csv")
data$ling = sapply(data$ling, as.character)
data [data$ling %in% c('yes','no'),] %>%
  na.omit() %>% 
  count(ling,stimulus) %>% 
  spread(key = ling, value = n) %>% 
  mutate(yes = ifelse(is.na(`yes`), as.integer(0), `yes`),  
         no = ifelse(is.na(`no`), as.integer(0), `no`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, yes, no) ->
  data_test
data_test = data_test[2:3,-1]
data_test
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)

Fisher's Exact Test for Count Data
data:  data_test
p-value = 0.0004936
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 1.316252 2.932600
sample estimates:
odds ratio 
  1.957039 
  
test = data_test
row.names(test)[1] <- 'Different'
row.names(test)[2] <- 'Identical'
test <- stack(test)
test$variant <- rep(c('Different','Identical'),2)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 14))) +
  geom_bar(stat="identity", position=position_dodge())


#состояние влияет на ответы

data = read.csv("analysis.csv")
data$real_condition = sapply(data$real_condition, as.character)
data [data$real_condition %in% c('liquid','soft', 'hard'),] %>%
  na.omit() %>% 
  count(real_condition,stimulus) %>% 
  spread(key = real_condition, value = n) %>% 
  mutate(liquid = ifelse(is.na(`liquid`), as.integer(0), `liquid`),  
         soft = ifelse(is.na(`soft`), as.integer(0), `soft`),
         hard = ifelse(is.na(`hard`), as.integer(0), `hard`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, liquid, soft, hard) ->
  data_test
data_test = data_test[2:3,-1]
#data_test
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)

	Fisher's Exact Test for Count Data with simulated p-value (based on 1e+05 replicates)
data:  data_test
p-value = 0.04941
alternative hypothesis: two.sided

test = data_test
row.names(test)[1] <- 'Different'
row.names(test)[2] <- 'Identical'
test <- stack(test)
test$variant <- rep(c('Different','Identical'),3)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 14))) +
  geom_bar(stat="identity", position=position_dodge())

#количество слогов влияет на ответы

data = read.csv("analysis.csv")
data$syllable = sapply(data$syllable, as.numeric)
data [data$syllable %in% c('1', '2'),] %>%
  na.omit() %>% 
  count(syllable,stimulus) %>% 
  spread(key = syllable, value = n) %>% 
  mutate(one.syll = ifelse(is.na(`1`), as.integer(0), `1`),  
         two.syll = ifelse(is.na(`2`), as.integer(0), `2`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, one.syll, two.syll) ->
  data_test
data_test = data_test[2:3,-1]
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)
#p-value = 0.0004465
test = data_test
row.names(test)[1] <- 'Different'
row.names(test)[2] <- 'Identical'
test <- stack(test)
test$variant <- rep(c('Different','Identical'),2)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 14))) +
  geom_bar(stat="identity", position=position_dodge())

#связь длины и влияния состояния (один слог): нет

data = read.csv("analysis.csv")
data [data$real_condition %in% c('liquid','soft','hard') & data$syllable == "1",]  %>% 
  na.omit() %>% 
  count(syllable, real_condition,stimulus) %>% 
  spread(key = real_condition, value = n) %>% 
  mutate(liquid = ifelse(is.na(`liquid`), as.integer(0), `liquid`),
         soft = ifelse(is.na(`soft`), as.integer(0), `soft`),  
         hard = ifelse(is.na(`hard`), as.integer(0), `hard`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, liquid, soft, hard) ->
  data_test
data_test = data_test[2:3,-1]
data_test
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)
#p-value = 0.1141

#связь длины и влияния состояния (два слога): когдв люди произносят два слога, на слушающих влияет состояние, значит, не можем сказать, что влияет по отдельности (то есть влияет какой-то общий фактор)

data = read.csv("analysis.csv")
data [data$real_condition %in% c('liquid','soft','hard') & data$syllable == "2",]  %>% 
  na.omit() %>% 
  count(syllable, real_condition,stimulus) %>% 
  spread(key = real_condition, value = n) %>% 
  mutate(liquid = ifelse(is.na(`liquid`), as.integer(0), `liquid`),
         soft = ifelse(is.na(`soft`), as.integer(0), `soft`),  
         hard = ifelse(is.na(`hard`), as.integer(0), `hard`),
         type = paste(stimulus)) %>% 
  ungroup() %>% 
  select(type, liquid, soft, hard) ->
  data_test
data_test = data_test[2:3,-1]
data_test
fisher.test(data_test,simulate.p.value=TRUE,B=1e5)
#p-value = 0.00433


#верно ли угадывают состояние (проверим двумя способами, получается одно число)

(choose(3,3)/27) #веротность угадать три из трех
((1-8/27)/27) #вероятность не угадать ничего
prop.test(247,640,p=(choose(3,3)/27), correct=FALSE)
prop.test(247,640,p=((1-8/27)/27) ,correct=FALSE)

data = read.csv("analysis.csv")
data$real_condition = sapply(data$real_condition, as.character)
data [data$real_condition %in% c('liquid', 'soft', 'hard'),] %>%
  na.omit() %>% 
  count(condition,real_condition) %>% 
  spread(key = real_condition, value = n) %>% 
  mutate(liquid = ifelse(is.na(`liquid`), as.integer(0), `liquid`),  
         soft = ifelse(is.na(`soft`), as.integer(0), `soft`),
         hard = ifelse(is.na(`hard`), as.integer(0), `hard`),
         type = paste(condition)) %>% 
  ungroup() %>% 
  select(type, liquid, soft, hard) ->
  data_test 

test = data_test [,-1]
row.names(test)[1] <- 'hard_choice'
row.names(test)[2] <- 'liquid_choice'
row.names(test)[3] <- 'soft_choice'
test <- stack(test)
test$variant <- rep(c('hard_choice','liquid_choice', 'soft_choice'),3)
ggplot(test, aes(x=ind, y=values, fill=variant)) +
  theme_bw()+
  theme_set(theme_bw()+theme(text = element_text(size = 14))) +
  geom_bar(stat="identity", position=position_dodge())

(choose(3,3)/27) #веротность угадать три из трех
((1-8/27)/27) #вероятность не угадать ничего

prop.test(247,640,p=(choose(3,3)/27) ,correct=FALSE)

1-sample proportions test without continuity correction

data:  247 out of 640, null probability (choose(3, 3)/27)
X-squared = 2184.4, df = 1, p-value < 2.2e-16
alternative hypothesis: true p is not equal to 0.03703704
95 percent confidence interval:
 0.3490088 0.4242273
sample estimates:
        p 
0.3859375 


prop.test(247,640,p=((1-8/27)/27) ,correct=FALSE)
	
1-sample proportions test without continuity correction

data:  247 out of 640, null probability ((1 - 8/27)/27)
X-squared = 3265.3, df = 1, p-value < 2.2e-16
alternative hypothesis: true p is not equal to 0.0260631
95 percent confidence interval:
 0.3490088 0.4242273
sample estimates:
        p 
0.3859375 

#логистическая регрессия, модель 

data_regression <- read.csv('analysis.csv',header=T,na.strings=c(""))
data_regression <- data_regression[-c(232, 471, 617),]
sapply(data_regression,function(x) sum(is.na(x)))
sapply(data_regression, function(x) length(unique(x)))
data <- subset(data_regression,select=c(3,4,5,6,8,15,16,17))
data <- data[-c(230:234),]

data_adjusted <- data %>%
  group_by(really,foreign,music,gender,ling,real_condition_2,syllable,stimulus) %>%
  summarise(n = n()) %>%
  spread(stimulus, n)

data_adjusted[is.na(data_adjusted)] <- 0
#model <- glm(cbind(same, different) ~ really * real_condition_2 + foreign,family=binomial(link='logit'),data=data_adjusted[!(data_adjusted$really %in% c('tonus.konus')),])
model <- glm(cbind(same, different) ~ really * real_condition_2 + foreign,family=binomial(link='logit'),data=data_adjusted)
summary(model)

exp(model$coefficients)
anova(model, test="Chisq")
1 - pchisq(36, df=6)
library(pscl)
pR2(model)
model$residuals

plot(model)

#graph by GM

library(tidyverse)
df <- read_csv("analysis.csv")
df %>% 
  count(really, stimulus, real_condition) %>% 
  group_by(really, real_condition) %>% 
  mutate(ratio = n/sum(n)) %>% 
  filter(stimulus == "different") %>% 
  ggplot(aes(really, ratio))+
  geom_col(fill = "lightblue")+
  geom_text(aes(label = round(ratio, 2)), nudge_y = 0.1)+
  coord_flip()+
  facet_wrap(~real_condition)+
  theme_bw()+
  labs(title = "Ratio of answers 'different'")
